services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-app-crud-post
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - mysql
    networks:
      - app-network-post-crud

  mysql:
    image: mysql
    restart: always
    container_name: laravel-app-crud-post-mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tsgDB
      MYSQL_USER: tsgUser
      MYSQL_PASSWORD: tsgPassword
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network-post-crud

networks:
  app-network-post-crud:
    driver: bridge

volumes:
  dbdata:
